[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.10.0",
    "gitpython>=2.1.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "pymurtree"
version = "0.0.1"
dependencies =[
    "pandas>=1.0.0",
    "numpy>=1.18.0",
]

[project.dynamic]
description = 'Python wrapper for the MurTree project'
authors = 'Jose Urra and Yasel Quintero'

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent", ]

[project.optional-dependencies]
dev = [
    "pytest>=5.3.0",
    "pytest-cov>=2.8.0",
]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src/pymurtree",
]

[project.urls]
